# Advantage is you get working CUDA+cuDNN+pytorch+torchvison versions.
#
# TODO: you must additionally install nVidia drivers, eg. on Ubuntu linux 
# `apt install nvidia-driver-440` (change the 440 for whatever version you need/have).
#
name: PyConEnv
#prefix: /your/custom/path/envs/PyConEnv
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python==3.6
  - pip
  - ipdb
  - jupyterlab
  - scikit-learn
  - scikit-image==0.14.3
  - matplotlib
  - git
  - seaborn
  - h5py
  - gdown # to download kitti dataset
  - unzip # to download kitti dataset
  - pip:
    - opencv-python 
    - tensorboard_logger
    - pillow==6.1.0
