# Advantage is you get working CUDA+cuDNN+pytorch+torchvison versions.
#
# TODO: you must additionally install nVidia drivers, eg. on Ubuntu linux 
# `apt install nvidia-driver-440` (change the 440 for whatever version you need/have).
#
name: PyConEnv
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1
  - numpy=1.18.1
  - opencv=3.4.2
  - pillow=7.0
  - pip=20.0
  - python=3.7.6
  - pytorch=1.6.0
  - torchvision=0.7
  - tensorboard=2.1
  - matplotlib=3.1.3
  - scikit-learn=0.22.1
  - pyyaml=5.3.1
  - jupyter
  - ipdb
  - nvidia-apex=0.1
