# Untested
_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "See Instructions"
  BACKBONE:
    FREEZE_AT: 0 
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ('kitti_train',)
  TEST: ('kitti_val',)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (12000, 16000) # From voc config
  MAX_ITER: 18000  # 17.4 epochs