_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "See Instructions"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 7
DATASETS:
  TRAIN: ('kitti_train',)
  TEST: ('kitti_val',)