_BASE_: "../Base-RCNN-FPN.yaml"
OUTPUT_DIR: "info200plus_60EP_mean"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530] #From infomin config
  PIXEL_STD: [58.395, 57.120, 57.375] #From infomin config
  WEIGHTS: "See Instructions"
  BACKBONE:
   FREEZE_AT: 0
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False #From infomin config
  #From infomin config
  #ROI_BOX_HEAD:
    #NAME: "FastRCNNConvFCHead"
    #NUM_CONV: 4
    #NUM_FC: 1
  ROI_HEADS:
    NUM_CLASSES: 7
#From infomin config
TEST:
  PRECISE_BN:
    ENABLED: True
#From voc config
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('kitti_train',)
  TEST: ('kitti_val',)
SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.01
  STEPS: (12000, 16000) # From voc config
  MAX_ITER: 20000  # 20 epochs
  # BIG NONO THIS WARMUP ITERS!
  # WARMUP_ITERS: 50
