_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
TEST:
  PRECISE_BN:
    ENABLED: True
SOLVER:
  IMS_PER_BATCH: 2
  STEPS: (60000, 80000)
  MAX_ITER: 90000