# WORKS!
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "See Instructions"
  BACKBONE:
    FREEZE_AT: 0
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
  ROI_HEADS:
    NUM_CLASSES: 20
TEST:
  PRECISE_BN:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2012_train',)
  TEST: ('voc_2012_val',)
SOLVER:
  IMS_PER_BATCH: 2
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  # BIG NONO THIS WARMUP ITERS!
  #WARMUP_ITERS: 100
